package com.enterprise.admin.entity;

/** In-app notification kinds. Each is generated by a real account or record change (see NotificationService). */
public enum NotificationType {
    ROLE_CHANGED,
    ACCOUNT_STATUS_CHANGED,
    ACCOUNT_DETAILS_CHANGED,
    PASSWORD_CHANGED,
    SECURITY_ALERT,
    EMPLOYEE_RECORD_UPDATED,
    ADMIN_GRANTED
}
